def SI(): 

   spam_indicators = [
    "subscribe to us",
    "buy premium fast just at 199",
    "make money at home",
    "download quick",
    "click fast",
    "buy this course",
    "limited time offer",
    "act now",
    "exclusive deal",
    "100% free",
    "risk-free trial",
    "get rich quick",
    "instant approval",
    "winner",
    "claim your prize",
    "no credit card required",
    "special promotion",
    "urgent",
    "offer expires soon",
    "money-back guarantee",
    "win big",
    "free gift",
    "as seen on",
    "lowest price",
    "fast cash",
    "work from home",
    "guaranteed results",
    "easy money",
    "double your income",
    "secret to success",
    "unlimited access",
    "click here",
    "amazing discount",
    "earn extra income",
    "free access",
    "hot deal",
    "cheap rates",
    "exclusive bonus",
    "limited availability",
    "hurry up",
    "congratulations, you’ve won",
    "save big",
    "get your free trial",
    "don't miss out",
    "we want your opinion",
    "your account has been compromised",
    "free trial",
    "free consultation",
    "cancel anytime",
    "biggest sale of the year",
    "guaranteed satisfaction",
    "just for you",
    "act fast",
    "best deal ever",
    "amazing offer",
    "lowest price guaranteed",
    "discount code",
    "unlock exclusive content",
    "check this out",
    "you’ve been selected",
    "last chance",
    "top-rated product",
    "order now",
    "trusted by thousands",
    "get yours today",
    "don’t wait",
    "exclusive opportunity",
    "this is not a scam",
    "official announcement",
    "attention required",
    "urgent action needed",
    "verify your account",
    "update your payment details",
    "claim your gift",
    "reward inside",
    "important notice",
    "win amazing prizes",
    "free webinar",
    "big savings",
    "learn the secret",
    "today only",
    "don’t miss your chance",
    "no risk involved",
    "sign up now",
    "upgrade your account",
    "satisfaction guaranteed",
    "receive instant rewards",
    "earn money instantly",
    "confirm your identity",
    "get approved instantly"
        ]
   return spam_indicators 